#!/bin/sh

portsnap fetch update
./portmerge svn svn://creme-brulee.marcuscom.com/ports-experimental/trunk/
./portmerge svn https://trillian.chruetertee.ch/svn/ports/trunk/
./portmerge svn https://github.com/cpu82/skype4-ports/trunk/
./portmerge svn https://github.com/brunolauze/freebsd-ports/trunk/
cp patches/samba41/patch-source4_lib_tls_wscript /usr/ports/net/samba41/files/
cp patches/ruby20/patch-ext__dl__extconf.rb /usr/ports/lang/ruby20/files/
find /usr/ports -name "Makefile" -exec  sed -i '' -e 's|graphics/jpeg|graphics/libjpeg-turbo|g' {} +
find /usr/ports -name "Makefile.common" -exec  sed -i '' -e 's|graphics/jpeg|graphics/libjpeg-turbo|g' {} +
echo "Linux CentOS 6.2 Qt 4.7 X11 port" > /usr/ports/x11-toolkits/linux-c6-qt47-x11/pkg-descr
echo "Linux CentOS 6.2 Qt 4.7 WebKit port" > /usr/ports/www/linux-c6-qt47-webkit/pkg-descr
echo "Qt 4 Framework" > /usr/ports/x11-toolkits/qt4-gui/pkg-descr
